### PR TITLE
update igpu patch

### PR DESCRIPTION
**Pull request by Lorys89**

### CODE REVIEW

**Comment by Lorys89** [comment]
test if work audio type c to hdmiand other

**Comment by aancw** [comment]
I will try this later after update to the new version EFI

**Comment by Lorys89** [comment]
> If you don't mind, can you share the step by step of this patch? Maybe I can try it without direct replace to plist file.

used all data method, and patched connectors according to guide on weg

**Comment by aancw** [comment]
Confirmed working using type-c port for monitor

Screen Shot 2021-10-10 at 20 41 43

**Comment by Lorys89** [comment]
> We can merge it and update to the release for https://github.com/Lovely-XPP/Dell-Latitude-E7480-Hackintosh/releases/tag/0.7.4.1 @Lovely-XPP
> 
> Thank you so much @Lorys89 for your effort

see my repo https://github.com/Lorys89/DELL_LATITUDE_7280

Dell Latitude 7280 is 7380 and 7480 have the same bios so same values for unlocking cfg and editing dvmt, read my repo, I changed those values, and see my ssdt, I use less patch than youDell Latitude 7280 is 7380 and 7480 have the same bios so same values for unlocking cfg and editing dvmt, read my repo, I changed those values, and see my ssdt, I use less patch than you 🙈

**Pull request merged**
