### PR TITLE
work gesture touchpad alps - config + kext mod

### PR DESCRIPTION
**Pull request by Lorys89**

### CODE REVIEW

**Comment by Lorys89** [comment]
test this fix :)
next pr I fix audio on all video outputs and improve the video patch. 
I own the Latitude 7280, which is the same as the 7380 and 7480.

**Comment by Lorys89** [comment]
> Mi dispiace che il kext non funzioni comunque per me.?

you tried this pr ?

**Comment by Lovely-XPP** [comment]
Yes, I also tried to change the order of kexts, it still can not work. BTW, if I add the kext you provided, my touchpad doesn't work.

**Comment by Lovely-XPP** [comment]
It works!!! Thanks a lot. I forgot to update I2C before.

**Pull request merged**
